Api/urls.py
from django.urls import path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"addInfo", views.InfoEjercicioViewSet, 'task')

urlpatterns = [
    path('getInfo/<int:rango>/', views.InfoEjercicioGet.as_view(), name='get_info'),
     path('getInfoEstudiantes/', views.ListadoEstudiantes.as_view(), name='estudiantes_por_profesor'),
]

urlpatterns += router.urls

AstroMath/urls.py
from django.contrib import admin
from django.urls import path, include
from Account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Account.urls')),
    path('Estudiante/', include('Student.urls')),
    path('Profesor/', include('Teacher.urls')),
    path('Api/', include('Api.urls'))
]

Student/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'Student'
urlpatterns = [
    path('', views.showMundos, name='Mundos'),
    path('Multiplicacion/', views.showEjerciciosMultiplicacion, name='Multiplicacion'),
    path('Resta/', views.showEjerciciosResta, name='Resta'),
    path('Suma/', views.showEjerciciosSuma, name='Suma'),
    path('Resta/Resultados/', views.showPantallaFinal, name='Resultados'),
    path('Suma/Resultados/', views.showPantallaFinal, name='Resultados'),
    path('Multiplicacion/Resultados/', views.showPantallaFinal, name='Resultados'),
    path('Perfil', views.showPerfil, name='Perfil'),
]

Student/models.py
from django.db import models

# Create your models here.

Student/views.py
from django.shortcuts import render
from Account.decorators import role_required
from Account import models

@role_required('Estudiante')
def showMundos(request):
    return render(request,'mundos.html')

def showEjerciciosMultiplicacion(request):
    return render(request, 'ejercicio-multiplicaciones.html')

def showEjerciciosSuma(request):
    return render(request, 'ejercicio.html')

def showEjerciciosResta(request):
    return render(request, 'ejercicio-resta.html')

def showPantallaFinal(request):
    return render(request, 'final-nivel.html')

def showPerfil(request):
    usuario = request.user
    try:
        perfil = models.Profile.objects.get(user=usuario)
    except models.Profile.DoesNotExist:
        perfil = None  

   
    recompensas_usuario = models.Usuario_Recompensa.objects.filter(id_user=usuario).select_related('id_recompensa')
    recompensas = [relacion.id_recompensa for relacion in recompensas_usuario]


    cantidad_recompensas = models.Recompensa.objects.count()

    while len(recompensas) < cantidad_recompensas:
        recompensas.append(None)


    context = {
        'username': usuario.username,
        'firstname': perfil.nombre,
        'apellidoPaterno': perfil.apellidoPaterno if perfil else None,
        'apellidoMaterno': perfil.apellidoMaterno if perfil else None,
        'paralelo': perfil.paralelo if perfil else None,
        'puntaje': perfil.puntaje if perfil else None,
        'recompensas': recompensas, 
        'cantidad_recompensas': cantidad_recompensas, 
    }

    return render(request, 'perfil.html', context)

Student/templates/ejercicio-multiplicaciones.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ejercicio-sumas/ejercicio.css' %}">
    <link rel="stylesheet" href="{% static 'ejercicio-multiplicaciones/tabla-multiplicar.css' %}">
    <title>Document</title>
</head>
<body class="body">
    <div id="particles-js">
    

    </div>
    <main class="principal-container">
        <div class="header">
            <div class="question-counter">1/5</div>
            <div class="exit-button">X</div>
        </div>
        <div class="mostrar">
            <div class="question" id="question"></div>
            <div class="answers" id="answers">
                <div class="option" id="option1"></div>
                <div class="option" id="option2"></div>
                <div class="option" id="option3"></div>
                <div class="option" id="option4"></div>
            </div>
        </div>
        <div class="pizarra-container" class="mostrar">
            <div class="toolbar">
                <button class="color-button" data-color="#FF0000" style="background-color: #FF0000;"></button>
                <button class="color-button" data-color="#000000" style="background-color: #000000;"></button>
                <button class="color-button" data-color="#0000FF" style="background-color: #0000FF;"></button>
                <button class="eraser-button" style="background-color: #FFFFFF;">🧽</button>
            </div>
            <canvas id="pizarra" width="800" height="400"></canvas>
            <div id="eraser-cursor"></div>
        </div>

        <section class="tablas-multiplicar">
            <div class="titulo-multiplicar">COMPLETA LA TABLA</div>
            <div class="tabla-container" id="tabla-container"></div>
            <div class="respuestas-container" id="respuestas-container"></div>
            <button class="next-problem">Aceptar</button>
        </section>
        
        
    </main>

    

    <div id="confirm-exit" style="display: none;" class="exit-confirmation">
        <p>¿Quieres salir del nivel?</p>
        <div class="confirmation-buttons">
            <button class="option-button" id="exit-confirmed">Salir</button>
            <button class="option-button" id="continue-level">Continuar</button>
        </div>
    </div>
</body>
<script>
    const pantallaMundos = "{% url 'Student:Mundos' %}"
</script>
<script src="{% static 'ejercicio-multiplicaciones/ejercicio-multiplicaciones.js' %}"></script>
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script src="{% static 'ejercicio-sumas/particlesjs-config.json' %}"></script>

<script>
    particlesJS.load('particles-js', '{% static "ejercicio-sumas/particlesjs-config.json" %}', function() {
        console.log('Particles.js config loaded');
    });
</script>
</html>

Student/templates/ejercicio-resta.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ejercicio-sumas/ejercicio.css' %}">
    
    <link rel="stylesheet" href="{% static 'ejercicio-restas/drag-drop-restas.css' %}">
    <title>Document</title>
</head>
<body class="body">
    <div id="particles-js">
        
    </div>
    <main class="principal-container">
        <div class="header">
            <div class="question-counter">1/5</div>
            <div class="exit-button">X</div>
        </div>
        <div class="question" id="question" style="display: none;"></div>
        <div class="answers" id="answers" style="display: none;">
            <div class="option" id="option1"></div>
            <div class="option" id="option2"></div>
            <div class="option" id="option3"></div>
            <div class="option" id="option4"></div>
        </div>
      

        <section class="drag-drop-section">
            <div class="title">
                <h2 class="drag-drop-title">AGARRA MISILES ----></h2>
                <div class="basket-container">
                    <img src="{% static 'images/contenedor-misiles.png' %}" alt="Contenedor de misiles" class="basket">
                </div>
            </div>
            
            <div class="drag-drop-equation">
                <div class="drop-box" id="box1"></div>
                <div class="operator">-</div>
                <div class="drop-box" id="box2"></div>
                <div class="operator">=</div>
                <div class="drop-area"></div>
            </div>
            <button class="next-problem">Aceptar</button>
        </section>
    </main>
    <div id="confirm-exit" style="display: none;" class="exit-confirmation">
        <p>¿Quieres salir del nivel?</p>
        <div class="confirmation-buttons">
            <button class="option-button" id="exit-confirmed">Salir</button>
            <button class="option-button" id="continue-level">Continuar</button>
        </div>
    </div>
    
</body>
<script>
    const pantallaMundos = "{% url 'Student:Mundos' %}"
    const imageUrl = "{% static 'images/misil.png' %}";
</script>
<script src="{% static 'ejercicio-restas/ejercicio-restas.js' %}"></script>
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script src="{% static 'ejercicio-sumas/particlesjs-config.json' %}"></script>

<script>
    particlesJS.load('particles-js', '{% static "ejercicio-sumas/particlesjs-config.json" %}', function() {
        console.log('Particles.js config loaded');
    });
    </script>
</html>

Student/templates/ejercicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ejercicio-sumas/ejercicio.css' %}">
    <title>Document</title>
</head>
<body class="body">
    <div id="particles-js">
        
    </div>
    <main class="principal-container">
        <div class="header">
            <div class="question-counter">1/5</div>
            <div class="exit-button">X</div>
        </div>
        <div class="question" id="question"></div>
        <div class="answers" id="answers">
            <div class="option" id="option1"></div>
            <div class="option" id="option2"></div>
            <div class="option" id="option3"></div>
            <div class="option" id="option4"></div>
        </div>
        
        <section class="drag-drop-section">
            <div class="middle-container">
                <div class="instructions-container">
                    <h1 class="title-instruction">COMPLETA LA CANTIDAD</h1>
                    <p class="instructions">
                        <br><br><br>Introduce los misiles<br><br>
                    </p>
                </div>
                <h3 class="apples-to-put">5</h3>
                <button class="next-problem">Aceptar</button>
            </div>
            
            
            <div class="bottom-container">
                <div class="left-container">
                    <img src="{% static 'images/contenedor-misiles.png' %}" alt="Contenedor de misiles" class="basket">
                </div>
                <div class="right-container">
                    <div class="drop-area"></div>
                </div>
            </div>
        </section>
        
    </main>
    <div id="confirm-exit" style="display: none;" class="exit-confirmation">
        <p>¿Quieres salir del nivel?</p>
        <div class="confirmation-buttons">
            <button class="option-button" id="exit-confirmed">Salir</button>
            <button class="option-button" id="continue-level">Continuar</button>
        </div>
    </div>
</body>
<script>
    const pantallaMundos = "{% url 'Student:Mundos' %}"
</script>
<script>
    const imageUrl = "{% static 'images/misil.png' %}";
</script>
<script src="{% static 'ejercicio-sumas/ejercicio.js' %}"></script>
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script src="{% static 'ejercicio-sumas/particlesjs-config.json' %}"></script>


<script>
particlesJS.load('particles-js', '{% static "ejercicio-sumas/particlesjs-config.json" %}', function() {
    console.log('Particles.js config loaded');
});
</script>

</html>

Student/templates/final-nivel.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'resultados/final-nivel.css' %}">
    <link rel="stylesheet" href="{% static 'resultados/loginResultado.css' %}">
    <link rel="stylesheet" href="{% static 'resultados/ejercicio.css' %}">
    
    <title>Document</title>
</head>
<body>
    <div id="result-box" class="result-box" >
        <div class="stars-back">
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
        </div>
        <h1 class="phrase"></h1>
        <img src="" alt="emotional-image" class="emotional-image">
        <div class="stars">
            <img src="{% static 'images/star-score.svg' %}" alt="star-score" class="star-score">
            <img src="{% static 'images/star-score.svg' %}" alt="star-score" class="star-score">
            <img src="{% static 'images/star-score.svg' %}" alt="star-score" class="star-score">
            <img src="{% static 'images/star-score.svg' %}" alt="star-score" class="star-score">
            <img src="{% static 'images/star-score.svg' %}" alt="star-score" class="star-score">
        </div>
        <p id="time-taken"></p>
        
        <div class="result-buttons">
            <button class="option-button" id="button-exit">Salir</button>
            <button class="option-button" id="button-reload">Reiniciar</buttton>
        </div>
        <div id="confirm-exit" style="display: none;" class="exit-confirmation">
            <p>¿Quieres salir del nivel?</p>
            <div class="confirmation-buttons">
                <button class="option-button" id="exit-confirmed">Salir</button>
                <button class="option-button" id="continue-level">Continuar</button>
            </div>
        </div>
        
    </div>
</body>
<script>
    const SumaUrl = "{% url 'Student:Suma' %}"
    const RestaUrl = "{% url 'Student:Resta' %}"
    const MultiplicacionUrl = "{% url 'Student:Multiplicacion' %}"
    const pantallaMundos = "{% url 'Student:Mundos' %}"
    const bueno = "{% static 'images/Good-Score.png' %}";
    const intermedio = "{% static 'images/Middle-Score.png' %}"
    const malo = "{% static 'images/Bad-Score.png' %}"
</script>
<script src="{% static 'resultados/final-nivel.js' %}"></script>
</html>

Student/templates/mundos.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'mundos/mundos.css' %}">
    <title>Document</title>
</head>
<body class="body">
  <a href="{% url 'Student:Perfil' %}">
    <img src="{% static 'images/Perfil.svg' %}" alt="Imagen en la esquina" class="imagen-esquina">
  </a>
    <main class="main-container">
        <div class="container">
            <div class="bubbles">
                <span style="--i:11;"></span>
                <span style="--i:12;"></span>
                <span style="--i:24;"></span>
                <span style="--i:10;"></span>
                <span style="--i:14;"></span>
                <span style="--i:23;"></span>
                <span style="--i:18;"></span>
                <span style="--i:16;"></span>
                <span style="--i:19;"></span>
                <span style="--i:20;"></span>
                <span style="--i:22;"></span>
                <span style="--i:25;"></span>
                <span style="--i:18;"></span>
                <span style="--i:21;"></span>
                <span style="--i:15;"></span>
                <span style="--i:13;"></span>
                <span style="--i:26;"></span>
                <span style="--i:17;"></span>
                <span style="--i:13;"></span>
                <span style="--i:28;"></span>
                <span style="--i:11;"></span>
                <span style="--i:12;"></span>
                <span style="--i:24;"></span>
                <span style="--i:10;"></span>
                <span style="--i:14;"></span>
                <span style="--i:23;"></span>
                <span style="--i:18;"></span>
                <span style="--i:16;"></span>
                <span style="--i:19;"></span>
                <span style="--i:20;"></span>
                <span style="--i:22;"></span>
                <span style="--i:25;"></span>
                <span style="--i:18;"></span>
                <span style="--i:21;"></span>
                <span style="--i:15;"></span>
                <span style="--i:13;"></span>
                <span style="--i:26;"></span>
                <span style="--i:17;"></span>
                <span style="--i:13;"></span>
                <span style="--i:28;"></span>
                <span style="--i:11;"></span>
                <span style="--i:12;"></span>
                <span style="--i:24;"></span>
                <span style="--i:10;"></span>
                <span style="--i:14;"></span>
                <span style="--i:23;"></span>
                <span style="--i:18;"></span>
                <span style="--i:16;"></span>
                <span style="--i:19;"></span>
                <span style="--i:20;"></span>
                <span style="--i:22;"></span>
                <span style="--i:25;"></span>
                <span style="--i:18;"></span>
                <span style="--i:21;"></span>
                <span style="--i:15;"></span>
                <span style="--i:13;"></span>
                <span style="--i:26;"></span>
                <span style="--i:17;"></span>
                <span style="--i:13;"></span>
                <span style="--i:28;"></span>
        
            </div>
        </div>
        <h1 class="titulo">Selecciona un planeta</h1>
        <h2 class="nombre-mundo"></h2>
        <div class="carrusel">
            <button class="flecha izquierda">&lt;</button>
            <div class="imagen-container"><img src="{% static  'images/Mundo-Sumas.png' %}" alt="Planeta 1" class="imagen activa"></div>
            <div class="imagen-container"><img src="{% static  'images/mundo-restas.png' %}" class="imagen siguiente" id="planeta-restas"></div>
            <div class="imagen-container"><img src="{% static  'images/Mundo-Multiplicaciones.png' %}" alt="Planeta 3" class="imagen inactiva"></div>
            
            <button class="flecha derecha">&gt;</button>
        </div>
        
        <button class="button-choose">Elegir</button>
    </main>

    <div class="niveles-overlay"></div>
    <section class="niveles">
      <div class="titulo-mundo"></div>
      <div class="nivel">
        
      </div>
    </section>
  <script src="{% static 'mundos/mundos.js' %}"></script>
  <script>
    const estrellaAmarilla = "{% static 'images/estrella-celeste.svg' %}";
    const estrellaGris = "{% static 'images/estrellaGris.svg' %}";
    function clickEjercicio() {
      document.querySelectorAll('.hab').forEach((nivel) => {
        nivel.addEventListener('click', () => {
            const numeroNivel = parseInt(nivel.querySelector('.nivel-numero').textContent);
            localStorage.setItem('nivelSeleccionado', numeroNivel);
            
            const tituloMundo = document.querySelector('.titulo-mundo').textContent; 
            localStorage.setItem('titulo-mundo', tituloMundo);
      
            if(tituloMundo==='Mundo de las Sumas'){
              window.location.href = "{% url 'Student:Suma' %}";
            }else if(tituloMundo==='Mundo de las Restas'){
              window.location.href = "{% url 'Student:Resta' %}";
            }else{
              window.location.href = "{% url 'Student:Multiplicacion' %}"
            }
        });
      });
    }
    
  </script>
  <script>
    const pantallaIndex = "{% url 'Index' %}"
  </script>
</body>
</html>

Student/templates/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Perfil/perfil.css' %}">
    <link rel="icon" href="../images/AstroMath.png">
    <title>AstroMath</title>
</head>
<body>
    <div id="particles-js">

    </div>
    <nav class="navbar">
        <div class="logo"><a href="{% url 'Student:Mundos' %}">VOLVER AL MENÚ PRINCIPAL</a></div>
        {% if user.is_authenticated %}
          <a href="{% url 'Logout' %}">CERRAR SESION</a>
        {% endif %}
        
    </nav>
    <div class="flip-card">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <div class="profile-image">
              <svg viewBox="0 0 122.88 122.88" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1" class="pfp"><g><path d="M61.44,0c8.32,0,16.25,1.66,23.5,4.66l0.11,0.05c7.47,3.11,14.2,7.66,19.83,13.3l0,0c5.66,5.65,10.22,12.42,13.34,19.95 c3.01,7.24,4.66,15.18,4.66,23.49c0,8.32-1.66,16.25-4.66,23.5l-0.05,0.11c-3.12,7.47-7.66,14.2-13.3,19.83l0,0 c-5.65,5.66-12.42,10.22-19.95,13.34c-7.24,3.01-15.18,4.66-23.49,4.66c-8.31,0-16.25-1.66-23.5-4.66l-0.11-0.05 c-7.47-3.11-14.2-7.66-19.83-13.29L18,104.87C12.34,99.21,7.78,92.45,4.66,84.94C1.66,77.69,0,69.76,0,61.44s1.66-16.25,4.66-23.5 l0.05-0.11c3.11-7.47,7.66-14.2,13.29-19.83L18.01,18c5.66-5.66,12.42-10.22,19.94-13.34C45.19,1.66,53.12,0,61.44,0L61.44,0z M16.99,94.47l0.24-0.14c5.9-3.29,21.26-4.38,27.64-8.83c0.47-0.7,0.97-1.72,1.46-2.83c0.73-1.67,1.4-3.5,1.82-4.74 c-1.78-2.1-3.31-4.47-4.77-6.8l-4.83-7.69c-1.76-2.64-2.68-5.04-2.74-7.02c-0.03-0.93,0.13-1.77,0.48-2.52 c0.36-0.78,0.91-1.43,1.66-1.93c0.35-0.24,0.74-0.44,1.17-0.59c-0.32-4.17-0.43-9.42-0.23-13.82c0.1-1.04,0.31-2.09,0.59-3.13 c1.24-4.41,4.33-7.96,8.16-10.4c2.11-1.35,4.43-2.36,6.84-3.04c1.54-0.44-1.31-5.34,0.28-5.51c7.67-0.79,20.08,6.22,25.44,12.01 c2.68,2.9,4.37,6.75,4.73,11.84l-0.3,12.54l0,0c1.34,0.41,2.2,1.26,2.54,2.63c0.39,1.53-0.03,3.67-1.33,6.6l0,0 c-0.02,0.05-0.05,0.11-0.08,0.16l-5.51,9.07c-2.02,3.33-4.08,6.68-6.75,9.31C73.75,80,74,80.35,74.24,80.7 c1.09,1.6,2.19,3.2,3.6,4.63c0.05,0.05,0.09,0.1,0.12,0.15c6.34,4.48,21.77,5.57,27.69,8.87l0.24,0.14 c6.87-9.22,10.93-20.65,10.93-33.03c0-15.29-6.2-29.14-16.22-39.15c-10-10.03-23.85-16.23-39.14-16.23 c-15.29,0-29.14,6.2-39.15,16.22C12.27,32.3,6.07,46.15,6.07,61.44C6.07,73.82,10.13,85.25,16.99,94.47L16.99,94.47L16.99,94.47z"></path></g></svg>
              <div class="name">
                {{ username }}
              </div>
            </div>
          </div>
          <div class="flip-card-back">
            <h1 class="titulo">MI PERFIL</h1>
            <div class="Description">
                <span class="datos-personales">Nombre: {{ firstname }}</span>
                <span class="datos-personales">Apellidos: {{ apellidoPaterno }} {{ apellidoMaterno }}</span>
                <span class="datos-personales">Paralelo: {{ paralelo }}</span>
                <span class="datos-personales">Puntaje: {{ puntaje }}</span>
            </div>
            <div class="logros">
                {% for recompensa in recompensas %}
                    {% if recompensa %}
                        <div class="logro">
                            <img src="{{ recompensa.imagen }}" alt="logro" class="imagen-logro">
                            <p class="nombre-logro">{{ recompensa.nombre }}</p>
                        </div>
                    {% else %}
                        <div class="logro">
                            <img src="https://i.imgur.com/jYTNZgL.png" alt="logro" class="imagen-logro">
                            <p class="nombre-logro">Necesitas más estrellas</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
      <script src="{% static 'Perfil/particlesjs-config-perfil.json' %}"></script>
    <script>
        particlesJS.load('particles-js', '{% static "Perfil/particlesjs-config-perfil.json" %}', function() {
            console.log('Particles.js config loaded');
        });
    </script>
</body>
</html>